language: generic

sudo: required

dist: trusty

services:
  - docker

before_install:
  - sudo pip install --user codecov

script:
  - docker run -v $TRAVIS_BUILD_DIR:/labyrinth lamtev/android:sdk25 /bin/bash -c " cd labyrinth/Labyrinth && cloc * && gradle build "

after_success:
  - cd Labyrinth && bash <(curl -s https://codecov.io/bash )
